name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca # master 2024-06
        with:
          scandir: '.'
          additional_files: 'shoo'

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Make executable
        run: chmod +x shoo

      - name: Test help
        run: ./shoo --help

      - name: Test version
        run: ./shoo --version

      - name: Test system scan (offline)
        run: ./shoo --system --offline

      - name: Test directory scan (offline)
        run: ./shoo --offline .
